# Travis Badge Markdown (add to README.md): [![Build Status](https://secure.travis-ci.org/jjman505/meteor-bitcoin-address.png?branch=master)](https://travis-ci.org/jjman505/meteor-bitcoin-address)
sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"